// zen-hotel-system/frontend/src/components/home/header.tsx
import Link from "next/link";
import Image from "next/image";
// Data
import { getSiteIdentity } from "@/lib/data";
// Components
import { HeaderNav } from "@/components/home/headerNav";
import { SignInButton } from "@/components/home/signInButton";

export async function Header() {
  const { name, logo } = await getSiteIdentity();
  
  return (
    <header className="border-b">
      <div className="container py-2 flex justify-between items-center">
        <Link href="/" className="flex items-center h-[60px] gap-x-3">
          <Image src={logo} alt="Chain Logo" width={60} height={60} />
          <div className="text-4xl text-foreground font-satisfy">{name}</div>
        </Link>
        <HeaderNav />
        <SignInButton />
      </div>
    </header>
  );
}

// apex-airline-system/avianca/avianca-frontend/src/lib/components/header/header.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { CircleUserRound } from "lucide-svelte";
  import logo from "$lib/assets/logo.png";
  import imageTab from "$lib/assets/Image-Tab.png";

  export let data: { user: User | null };
</script>

<link class="tabimage" rel="icon" type="image/png" href={imageTab}/> 

<header class="h-20 border-b">
  <div class="flex h-full container justify-between items-center">
    <a href="/">
      <img src={logo} alt="Avianca Logo" class="w-[202px] h-[60px]" />
    </a>
    <nav class="flex gap-x-3 text-sm font-bold">
      <Button href="" variant="ghost" class="font-bold">About Us</Button>
    </nav>
    {#if data.user}
      <Button href="/user/dashboard" variant="ghost" class="font-bold">
        <CircleUserRound class="mr-2" />{data.user.firstName +
          " " +
          data.user.lastName}
      </Button>
    {:else}
      <Button href="/signin">
        Join | Sign In <CircleUserRound class="ml-2" />
      </Button>
    {/if}
  </div>
</header>
