// apex-airline-system/frontend/src/routes/user/administration/users/+page.svelte
<script lang="ts">
  import UserCard from "$lib/components/user/users/UserCard.svelte";
  import UserCardSkeleton from "$lib/components/user/users/UserCardSkeleton.svelte";
  export let data;
  export let form;
</script>

<div class="flex items-center mt-4 mb-8 gap-x-3">
  <h1 class="text-xl font-bold">Users Administration</h1>
</div>

<div class="flex flex-col gap-y-8">
  {#await data.users}
    {#each Array(3).fill(0) as _}
      <UserCardSkeleton />
    {/each}
  {:then users}
    {#each users as user}
      <UserCard {form} {user} />
    {/each}
  {:catch error}
    <p>{error.message}</p>
  {/await}
</div>

// zen-hotel-system/frontend/src/components/user/administration/users.tsx
import { getUsers } from "@/lib/data";
import { UserCard } from "@/components/user/userCard";

export async function Users() {
  const users = await getUsers();

  return (
    <>
      {users.length === 0 && (
        <div className="flex justify-center items-center h-full">
          <h1 className="text-xl font-bold">No Users Found</h1>
        </div>
      )}
      {users.map((user: User) => (
        <UserCard key={user._id} user={user} />
      ))}
    </>
  );
}
