// apex-airline-system/frontend/src/routes/user/administration/users/+page.svelte
<script lang="ts">
  import UserCard from "$lib/components/user/users/UserCard.svelte";
  import UserCardSkeleton from "$lib/components/user/users/UserCardSkeleton.svelte";
  export let data;
  export let form;
</script>

<div class="flex items-center mt-4 mb-8 gap-x-3">
  <h1 class="text-xl font-bold">Users Administration</h1>
</div>

<div class="flex flex-col gap-y-8">
  {#await data.users}
    {#each Array(3).fill(0) as _}
      <UserCardSkeleton />
    {/each}
  {:then users}
    {#each users as user}
      <UserCard {form} {user} />
    {/each}
  {:catch error}
    <p>{error.message}</p>
  {/await}
</div>

// zen-hotel-system/frontend/src/app/(user)/administration/users/page.tsx
import { Suspense } from "react";
// Components
import { Users } from "@/components/user/administration/users";
import { UserCardSkeleton } from "@/components/skeletons/userCardSkeleton";
import { SectionTitle } from "@/components/user/sectionTitle";

export default function UsersAdministrationHome() {
  return (
    <>
      <SectionTitle
        title="Users Administration"
        description="Visualize and Manage Users Information"
      />
      <Suspense
        fallback={
          <div className="flex flex-col gap-y-3 mb-8 mr-8">
            {Array(2)
              .fill(0)
              .map((_, index) => (
                <UserCardSkeleton key={index} />
              ))}
          </div>
        }
      >
        <div className="flex flex-col gap-y-3 mb-8 mr-8">
          <Users />
        </div>
      </Suspense>
    </>
  );
}
