// zen-hotel-system/marriot/frontend/src/components/home/header.tsx
import Image from "next/image";
import Link from "next/link";
import { HeaderNav } from "@/components/home/headerNav";
import { SignInButton } from "@/components/home/signInButton";

export function Header() {
  return (
    <header className="h-20 border-b shadow">
      <div className="container flex justify-between items-center h-full">
        <Link href="/">
          <Image
            src={`/zen-logo.png`}
            alt="Zen Hotels Logo"
            width="150"
            height="60"
            priority
          />
        </Link>
        <HeaderNav />
        <SignInButton />
      </div>
    </header>
  );
}

// apex-airline-system/qatar-airways/src/lib/components/header/header.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { CircleUserRound } from "lucide-svelte";
  import logo from "$lib/assets/logo.png";
</script>

<header class="h-20 border-b">
  <div class="flex h-full container justify-between items-center">
    <a href="/">
      <img src={logo} alt="Avianca Logo" />
    </a>
    <nav class="flex gap-x-3 text-sm font-bold">
      <div>About Us</div>
    </nav>
    <Button>Join | Sign In <CircleUserRound class="ml-2" /></Button>
  </div>
</header>
