// zen-hotel-system/marriot/frontend/src/app/(user)/dashboard/page.tsx
import { cookies } from "next/headers";
// Components
import { SectionTitle } from "@/components/user/sectionTitle";
// JSON Web Token Utilities
import * as jose from "jose";

export default async function DashboardHome() {
  const token = cookies().get("token");

  const { payload }: { payload: User } = await jose.jwtVerify(
    token!.value,
    new TextEncoder().encode(process.env.JWT_SECRET)
  );

  return (
    <>
      <SectionTitle
        title="Dashboard"
        description="View Your Important Information"
      />
      <div className="flex flex-col gap-y-5 p-3 border rounded-lg">
        <div>
          <div className="flex flex-col gap-x-2">
            <div className="font-bold">Welcome Back,</div>
            <div>{payload.firstName + " " + payload.lastName}</div>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-y-5">
          <UserSection title="First Name" value={payload.firstName} />
          <UserSection title="Last Name" value={payload.lastName} />
          <UserSection title="Email" value={payload.email} />
          <UserSection title="Age" value={payload.age} />
          <UserSection title="Passport Number" value={payload.passportNumber} />
          <UserSection
            title="Country of Origin"
            value={payload.originCountry}
          />
        </div>
      </div>
    </>
  );
}

function UserSection({
  title,
  value,
}: {
  title: string;
  value: string | number;
}) {
  return (
    <div className="flex flex-col">
      <div className="font-bold text-sm">{title}</div>
      <div className="text-muted-foreground text-sm">{value}</div>
    </div>
  );
}

// apex-airline-system/avianca/avianca-frontend/src/routes/user/dashboard/+page.svelte
<script lang="ts">
  import UserInfo from "$lib/components/user/dashboard/userInfo.svelte";
  import messi from "$lib/assets/messi.jpg";

  export let data;

  const userInfo = [
    { key: "Full Name", value: data.user.firstName + " " + data.user.lastName },
    { key: "Email", value: data.user.email },
    { key: "Password", value: "*********" },
    { key: "Age", value: data.user.age },
    { key: "Country of Origin", value: data.user.originCountry },
    { key: "Passport Number", value: data.user.passportNumber },
  ];
</script>

<h1 class="text-xl font-bold mb-8">Dashboard</h1>
<div class="grid grid-cols-2 gap-x-8">
  <div class="flex flex-col gap-y-3">
    <div class="font-bold">Profile</div>
    <div class="flex flex-col gap-y-2 border rounded-lg p-3">
      <img
        src={messi}
        alt="User Profile"
        class="rounded-full w-[4.5rem] h-[4.5rem] self-center object-cover animate-spin"
      />
      {#each userInfo as user}
        <UserInfo key={user.key} value={user.value} />
      {/each}
    </div>
  </div>
  <div class="flex flex-col gap-y-3">
    <div class="font-bold">Flights Overview</div>
    <div class="flex flex-col gap-y-2 border rounded-lg p-3">
      <div class="text-sm font-medium">No flights booked</div>
    </div>
  </div>
</div>
