// zen-hotel-system/frontend/src/components/user/administration/users.tsx
import { getUsers } from "@/lib/data";
import { UserCard } from "@/components/user/userCard";

export async function Users() {
  const users = await getUsers();

  return (
    <>
      {users.length === 0 && (
        <div className="flex justify-center items-center h-full">
          <h1 className="text-xl font-bold">No Users Found</h1>
        </div>
      )}
      {users.map((user: User) => (
        <UserCard key={user._id} user={user} />
      ))}
    </>
  );
}

// apex-airline-system/avianca/avianca-frontend/src/routes/user/administration/users/+page.svelte
<script lang="ts">
  import UserCard from "$lib/components/user/users/UserCard.svelte";

  export let data;
  export let form;
</script>

<h1 class="text-xl font-bold mb-8">Users Administration</h1>
<div class="flex flex-col gap-y-3">
  {#each data.users as user}
    <UserCard {form} user={user} />
  {/each}
</div>
