// apex-airline-system/qatar-airways/src/lib/components/user/navBar.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import {
    LayoutDashboard,
    BedDouble,
    Table2,
    Bolt,
    WalletCards,
    AreaChart,
    LogOut,
  } from "lucide-svelte";

  const routes = [
    {
      value: "dashboard",
      label: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
    },
    {
      value: "flights",
      label: "Flights",
      href: "/reservations",
      icon: BedDouble,
    },
    {
      value: "inventory",
      label: "Inventory",
      href: "/inventory",
      icon: Table2,
    },
    {
      value: "administration",
      label: "Administration",
      href: "/administration",
      icon: Bolt,
    },
    {
      value: "purchase-logs",
      label: "Purchase Logs",
      href: "/purchase-logs",
      icon: WalletCards,
    },
    {
      value: "analytics",
      label: "Analytics",
      href: "/analytics",
      icon: AreaChart,
    },
  ];
</script>

<nav
  class="flex flex-col gap-y-3 py-8 pr-8 border-r sticky top-0 overflow-y-auto"
>
  {#each routes as route}
    <Button href={route.href} class="justify-normal">
      <svelte:component this={route.icon} class="shrink-0 mr-2 h-4 w-4" />
      {route.label}
    </Button>
  {/each}
  <Button class="justify-normal">
    <LogOut class="shrink-0 mr-2 h-4 w-4" />Log Out
  </Button>
</nav>

// zen-hotel-system/frontend/src/components/user/navBar.tsx
"use client";
import { usePathname } from "next/navigation";
// Data
import { logOut } from "@/lib/actions";
// Components
import { Button } from "@/components/ui/button";
import { NavButton } from "@/components/user/navButton";
// Icons
import {
  LayoutDashboard,
  WalletCards,
  AreaChart,
  LogOut,
  BedDouble,
  Table2,
  Bolt,
} from "lucide-react";

const routes = [
  {
    value: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: <LayoutDashboard className="w-4 h-4 mr-3 shrink-0" />,
  },
  {
    value: "reservations",
    label: "Reservations",
    href: "/reservations",
    icon: <BedDouble className="w-4 h-4 mr-3 shrink-0" />,
  },
];

const adminRoutes = [
  {
    value: "inventory",
    label: "Inventory",
    href: "/inventory",
    icon: <Table2 className="w-4 h-4 mr-3 shrink-0" />,
  },
  {
    value: "administration",
    label: "Administration",
    href: "/administration",
    icon: <Bolt className="w-4 h-4 mr-3 shrink-0" />,
  },
  {
    value: "purchase-logs",
    label: "Purchase Logs",
    href: "/purchase-logs",
    icon: <WalletCards className="w-4 h-4 mr-3 shrink-0" />,
  },
  {
    value: "analytics",
    label: "Analytics",
    href: "/analytics",
    icon: <AreaChart className="w-4 h-4 mr-3 shrink-0" />,
  },
];

export function NavBar({ isAdmin }: { isAdmin: boolean }) {
  const currentPath = usePathname();
  return (
    <nav className="flex flex-col py-8 pr-8 border-r gap-y-3 shrink-0 sticky top-0 overflow-y-auto custom-scrollbar">
      {routes.map((route) => (
        <NavButton
          variant={currentPath.includes(route.value) ? "default" : "secondary"}
          key={route.value}
          href={route.href}
          icon={route.icon}
        >
          {route.label}
        </NavButton>
      ))}
      {isAdmin &&
        adminRoutes.map((route) => (
          <NavButton
            variant={
              currentPath.includes(route.value) ? "default" : "secondary"
            }
            key={route.value}
            href={route.href}
            icon={route.icon}
          >
            {route.label}
          </NavButton>
        ))}
      <Button
        onClick={async () => {
          await logOut();
        }}
        className="justify-normal"
      >
        <LogOut className="w-4 h-4 mr-3 shrink-0" />
        Log Out
      </Button>
    </nav>
  );
}
