// zen-hotel-system/frontend/src/components/searchBar.tsx
import { Input } from "@/components/ui/input";
import { DatePicker } from "@/components/datePicker";
import { Button } from "@/components/ui/button";
import { NumberPicker } from "@/components/numberPicker";
import { LocationPicker } from "@/components/locationPicker";

function SearchBarElement({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-y-2">
      <div className="text-foreground font-bold tracking-tight text-base">
        {title}
      </div>
      {children}
    </div>
  );
}

export function SearchBar() {
  return (
    <div className="flex container items-center justify-center ">
      <div className="flex gap-x-3 bg-background  rounded-md p-3 items-center">
        <SearchBarElement title="Where to?">
          <LocationPicker />
        </SearchBarElement>
        <SearchBarElement title="When?">
          <DatePicker />
        </SearchBarElement>
        <SearchBarElement title="How many?">
          <NumberPicker />
        </SearchBarElement>
        <div className="flex flex-col gap-y-2">
          <div className="text-background font-bold">Search</div>
          <Button>Find Hotels</Button>
        </div>
      </div>
    </div>
  );
}

// apex-airline-system/qatar-airways/src/lib/components/searchBar/searchBar.svelte
<script lang="ts">
  import LocationPicker from "$lib/components/searchBar/locationPicker.svelte";
  import DateRangePicker from "$lib/components/searchBar/dateRangePicker.svelte";
  import NumberPicker from "$lib/components/searchBar/numberPicker.svelte";
  import { Button } from "$lib/components/ui/button";
</script>

<div class="bg-white rounded-md p-3 shadow border flex gap-x-3 flex-wrap gap-y-3">
  <div class="flex flex-col gap-y-2">
    <div class="font-bold">From?</div>
    <LocationPicker />
  </div>
  <div class="flex flex-col gap-y-2">
    <div class="font-bold">To?</div>
    <LocationPicker />
  </div>
  <div class="flex flex-col gap-y-2">
    <div class="font-bold">When?</div>
    <DateRangePicker />
  </div>
  <div class="flex flex-col gap-y-2">
    <div class="font-bold">How Many?</div>
    <NumberPicker />
  </div>
  <div class="flex flex-col gap-y-2">
    <div class="text-background">Find</div>
    <Button>
      Find Flights
    </Button>
  </div>
</div>
