// nexus-agency-system/frontend/src/lib/components/roomsearch/roomCard.svelte
<script lang="ts">
  import { Star, MapPin } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import HotelCardModal from "$lib/components/hotelseach/hotelCardModal.svelte";
  import { goto } from "$app/navigation";
  import type { DateRange } from "bits-ui";
  import { page } from "$app/stores";
  import { BedDouble, UserRound } from "lucide-svelte";

  export let room;
  export let guests: string | null;
  export let user: User;
  // export let form;
</script>

{#each Object.keys(room) as roomType}
  {#if roomType == "juniorSuite" || roomType == "standardSuite" || roomType == "bigSuite" || roomType == "doubleSuite"}
    <article
      class="border rounded-md grid-cols-[0.75fr_1fr] grid h-72 mt-10 mb-20"
    >
      <div class="relative">
        <img
          src={room[roomType].picture}
          alt={`${room[roomType].picture} Hotel Image`}
          class="object-cover rounded-l-md"
        />
      </div>
      <div class="flex flex-col justify-between rounded-r-md bg-background">
        <div class="flex flex-col gap-y-1 p-4 h-full">
          <div class="font-medium tracking-tight text-xl">
            {#if roomType == "juniorSuite"}
            Juior Suite
            {:else if roomType == "standardSuite"}
            Standard Suite
            {:else if roomType == "doubleSuite"}
            Double Suite
            {:else}
            Big Suite
            {/if}
          </div>
          <div class="flex gap-x-1 text-sm items-center text-muted-foreground">
            <BedDouble class="w-4 h-4 text-black fill-yellow-500" />
            <div>{Math.round(room[roomType].beds.amount)}</div>
            <div>{room[roomType].beds.size} Size Beds</div>
            <div>|</div>
            <UserRound class="w-4 h-4 text-black fill-red-700" />
            <div>{room[roomType].maxOccupancy} maximum occupancy</div>
          </div>
          <p class="text-sm line-clamp-3 mt-4">{room[roomType].description}</p>
        </div>
        <div class="ml-3">
          <!-- Lower  -->
          <!-- <HotelCardModal {hotel} {user} /> -->
        </div>
        <div class="border-t p-3 flex justify-end gap-x-3">
          <div class="flex gap-x-1 items-end">
            <div class="font-bold text-xl">
              {room[roomType].price}
            </div>
            <div class="text-sm mb-[2px] text-muted-foreground">
              USD / Night
            </div>
          </div>
          <Button>Continue</Button>
        </div>
      </div>
    </article>
  {/if}
{/each}

// zen-hotel-system/frontend/src/components/rooms/roomCard.tsx
import Image from "next/image";
import Link from "next/link";
// Components
import { RoomDialog } from "@/components/rooms/roomDialog";
// UI Components
import { Button } from "@/components/ui/button";
import { BedDouble, UserRound } from "lucide-react";

export function RoomCard({
  hotelId,
  suite,
  searchParams,
}: {
  hotelId: string;
  suite: {
    type: string;
    picture: string;
    price: number;
    description: string;
    maxOccupancy: number;
    beds: { amount: number; size: string };
    roomSize: string;
    totalRooms: number;
    reservedRooms: number;
  };
  searchParams: HotelSearchParams;
}) {
  return (
    <article className="border rounded-md grid-cols-[0.75fr_1fr] grid h-72">
      <div className="relative">
        <Image
          src={suite.picture}
          alt={`${suite.type} Image`}
          fill
          className="object-cover rounded-l-md"
        />
      </div>
      <div className="flex flex-col justify-between rounded-r-md bg-background">
        <div className="flex flex-col gap-y-1 p-4 h-full">
          <div className="font-medium tracking-tight text-xl">
            {suite.type === "juniorSuite"
              ? "Junior Suite"
              : suite.type === "standardSuite"
              ? "Standard Suite"
              : suite.type === "doubleSuite"
              ? "Double Suite"
              : "Big Suite"}
          </div>
          <div className="flex gap-x-1 text-sm items-center text-muted-foreground">
            <BedDouble className="w-4 h-4 text-black fill-yellow-500" />
            <div>
              {suite.beds.amount} {suite.beds.size} Size beds
            </div>
            <div>|</div>
            <UserRound className="w-4 h-4 text-black fill-red-700" />
            <div>{suite.maxOccupancy} maximum occupancy</div>
          </div>
          <p className="text-sm line-clamp-3 mt-4">{suite.description}</p>
          <RoomDialog
            hotelId={hotelId}
            suite={suite}
            searchParams={searchParams}
          />
        </div>
        <div className="border-t p-3 flex justify-end gap-x-3">
          <div className="flex gap-x-1 items-end">
            <div className="font-bold text-xl">{suite.price}</div>
            <div className="text-sm mb-[2px] text-muted-foreground">
              USD / Night
            </div>
          </div>
          {Number(searchParams.guests) > suite.maxOccupancy ? (
            <Button disabled>Not Enough Space</Button>
          ) : (
            <Button asChild>
              <Link
                href={`/checkout/${hotelId}/?${new URLSearchParams(
                  searchParams
                ).toString()}&type=${suite.type}`}
              >
                Continue
              </Link>
            </Button>
          )}
        </div>
      </div>
    </article>
  );
}
