// zen-hotel-system/frontend/src/components/user/analytics/locationPicker.tsx
"use client";
import { useState } from "react";
import { cn } from "@/lib/utils";
// UI Components
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
// Icons
import { Check, ChevronsUpDown } from "lucide-react";

export function LocationPicker({
  locations,
  currentLocation,
  setLocation,
}: {
  locations: string[];
  currentLocation: string;
  setLocation: (location: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState(currentLocation.toLowerCase());

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-96 justify-between"
        >
          {value
            ? locations.find((location) => location.toLowerCase() === value)
            : "City"}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-96 p-0">
        <Command>
          <CommandInput placeholder="Search location..." />
          <CommandEmpty>No destinations found.</CommandEmpty>
          <CommandGroup>
            {locations.map((location) => (
              <CommandItem
                key={location}
                value={location}
                onSelect={(currentValue) => {
                  setValue(currentValue === value ? "" : currentValue);
                  setLocation(currentValue === value ? "" : location);
                  setOpen(false);
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === location.toLowerCase()
                      ? "opacity-100"
                      : "opacity-0"
                  )}
                />
                {location}
              </CommandItem>
            ))}
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

// nexus-agency-system/frontend/src/lib/components/hotelBar/locationPicker.svelte
<script lang="ts">
  import { Check, ChevronsUpDown } from "lucide-svelte";
  import * as Command from "$lib/components/ui/command";
  import * as Popover from "$lib/components/ui/popover";
  import { Button } from "$lib/components/ui/button";
  import { cn } from "$lib/utils";
  import { tick } from "svelte";
  
  export let cities: City[] = [];
    
  let open = false;
  
  export let value = "";

  $: selectedValue =
    cities.find((f) => f.cityId === value)?.name ?? "Select a location...";
  function closeAndFocusTrigger(triggerId: string) {
    open = false;
    tick().then(() => {
      document.getElementById(triggerId)?.focus();
    });
  }
</script>

<Popover.Root bind:open let:ids>
  <Popover.Trigger asChild let:builder>
    <Button
      builders={[builder]}
      variant="outline"
      role="combobox"
      aria-expanded={open}
      class="w-[200px] justify-between"
    >
      {selectedValue}
      <ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
    </Button>
  </Popover.Trigger>
  <Popover.Content class="w-[200px] p-0">
    <Command.Root>
      <Command.Input placeholder="Search for a location..." />
      <Command.Empty>No location found.</Command.Empty>
      <Command.Group>
        {#each cities as city}
          <Command.Item
            value={city}
            onSelect={(currentValue) => {
              value = currentValue;
              closeAndFocusTrigger(ids.trigger);
            }}
          >
            <Check
              class={cn(
                "mr-2 h-4 w-4",
                value !== city && "text-transparent"
              )}
            />
            {city}
          </Command.Item>
        {/each}
      </Command.Group>
    </Command.Root>
  </Popover.Content>
</Popover.Root>
